### PR TITLE
[TLM CI] Add unique queries for tests + add re-run failed tests ci

### PR DESCRIPTION
**Pull request by ulya-tkch**

### CODE REVIEW

**Comment by jas2600** [comment]
> /test-tlm ✨ **Starting TLM tests...** ✨ If you want to run the TLM tests again (in case they failed or you have further updates to the TLM code), comment '/test-tlm' on this PR. [View full GitHub Actions run log](https://github.com/cleanlab/cleanlab-studio/actions/runs/10964775291) ✨ **Tests completed!** ✨ TLM Tests Results: ❌❌❌❌❌ TLM Property Tests Results: ✅✅✅✅✅ Click the Github Actions run log for more information. ✨ **Tests completed!** ✨ TLM Tests Results: ❌❌❌❌❌ TLM Property Tests Results: ✅✅✅✅✅ Click the Github Actions run log for more information. ✨ **Tests completed!** ✨ TLM Tests Results: ✅✅✅✅✅ TLM Property Tests Results: ✅✅✅✅✅ Click the Github Actions run log for more information.

why we have 3 outputs now?

**Comment by ulya-tkch** [comment]
> why we have 3 outputs now?

I was manually re-triggering the tests since the property tests were passing I was just calling "re-run failed jobs". This still triggers the print and is expected but does not trigger the starting tests print since we don't start the test with test-tlm

**Review by jas2600 — APPROVED** [review]

**Pull request merged**
