### PR TITLE
print link to cleanset when ready

### PR DESCRIPTION
**Pull request by axl1313**
This PR updates the `wait_until_cleanset_ready()` method to print a link to the cleanset page when ready to make it easier for a user to navigate to their cleanset

### CODE REVIEW

**Comment by ryansingman** [comment]
Does this print belong in the open source? `wait_until_cleanset_ready` will be used in use cases outside of in Jupyter notebooks, and it's generally best practice to avoid extraneous prints

**Comment by axl1313** [comment]
> Does this print belong in the open source? `wait_until_cleanset_ready` will be used in use cases outside of in Jupyter notebooks, and it's generally best practice to avoid extraneous prints

Ah that's a good point. I guess when running in a script this print is unlikely to be useful. What if we do a check if running in Jupyter notebook and print if so?

**Comment by ryansingman** [comment]
> > Does this print belong in the open source? `wait_until_cleanset_ready` will be used in use cases outside of in Jupyter notebooks, and it's generally best practice to avoid extraneous prints
> 
> Ah that's a good point. I guess when running in a script this print is unlikely to be useful. What if we do a check if running in Jupyter notebook and print if so?

That's a bit better, but I'm still not sure why this code should go in `cleanlab-studio` as opposed to in the notebooks themselves. Is there a reason to do this here?

**Comment by axl1313** [comment]
> > > Does this print belong in the open source? `wait_until_cleanset_ready` will be used in use cases outside of in Jupyter notebooks, and it's generally best practice to avoid extraneous prints
> > 
> > 
> > Ah that's a good point. I guess when running in a script this print is unlikely to be useful. What if we do a check if running in Jupyter notebook and print if so?
> 
> That's a bit better, but I'm still not sure why this code should go in `cleanlab-studio` as opposed to in the notebooks themselves. Is there a reason to do this here?

I just figured it'd be useful for a lot of cases since you have to open the project in the web UI to do things like make corrections, rerun cleanlab, deploy models and this way we wouldn't need to update all the tutorials separately. What if we updated the [postfix str](https://github.com/cleanlab/cleanlab-studio/blob/47902969e14c2145d67e1d9cb9f8b751a2c926d7/cleanlab_studio/internal/clean_helpers.py#L40) on the tqdm progress to include the cleanset link when the cleanset's ready instead of printing a separate message?

**Comment by ryansingman** [comment]
> > > > Does this print belong in the open source? `wait_until_cleanset_ready` will be used in use cases outside of in Jupyter notebooks, and it's generally best practice to avoid extraneous prints
> > > 
> > > 
> > > Ah that's a good point. I guess when running in a script this print is unlikely to be useful. What if we do a check if running in Jupyter notebook and print if so?
> > 
> > 
> > That's a bit better, but I'm still not sure why this code should go in `cleanlab-studio` as opposed to in the notebooks themselves. Is there a reason to do this here?
> 
> I just figured it'd be useful for a lot of cases since you have to open the project in the web UI to do things like make corrections, rerun cleanlab, deploy models and this way we wouldn't need to update all the tutorials separately. What if we updated the [postfix str](https://github.com/cleanlab/cleanlab-studio/blob/47902969e14c2145d67e1d9cb9f8b751a2c926d7/cleanlab_studio/internal/clean_helpers.py#L40) on the tqdm progress to include the cleanset link when the cleanset's ready instead of printing a separate message?

My general feeling here is that explicit > implicit. I do definitely agree that this will be useful in a lot of cases, but I think that that's only in tutorials and jupyter notebooks. How would a solution like adding a parameter (`show_cleanset_link`, default `False`) to the method feel to you? I like that it's more explicit and also prevents us from printing out links in the console for API users (which I think is clunky -- it gives the impression that the app is only usable via the UI)

**Review by ryansingman — APPROVED** [review]

**Pull request merged**
