### PR TITLE
Rename TLMHybrid to TLMLite

### PR DESCRIPTION
**Pull request by huiwengoh**

### CODE REVIEW

**Comment by jwmueller** [comment]
name change is good and I like the copy saying `TLM Lite`.

Will leave checking the code actually works though to @jas2600 (and that it's been updated everywhere necessary)

**Comment by jas2600** [comment]
The changes LGTM. But somehow when i tried to generate the docs website locally i got the following errors, which doesn't seems related though. And it only happens with this branch. The main branch works fine to generate the docs.



SyntaxError: /Users/jay/workspaces/cleanlab-studio-docs/docs/autogenerated/reference/cleanlab_studio.studio.inference.md: Expected corresponding JSX closing tag for . (9:163)
   7 |
   8 | {/* markdownlint-disable */}
>  9 | <a href="../../../cleanlab_studio/studio/inference#L0"></a>
     |                                                                                                                                                                    ^
  10 | <h1 {...{"id":"module-cleanlab_studiostudioinference"}}><kbd>{`module`}</kbd>{` `}<inlineCode parentName="h1">{`cleanlab_studio.studio.inference`}</inlineCode></h1>
  11 | <p>{`Methods for interfacing with deployed ML models (to produce predictions). `}</p>
  12 | <p><strong parentName="p">{`This module is not meant to be imported and used directly.`}</strong>{` Instead, use `}<a parentName="p" {...{"href":"../studio/#method-get_model"}}><inlineCode parentName="a">{`Studio.get_model()`}</inlineCode></a>{` to instantiate a `}<a parentName="p" {...{"href":"#class-model"}}>{`Model`}</a>{` object. `}</p>
SyntaxError: /Users/jay/workspaces/cleanlab-studio-docs/docs/autogenerated/reference/cleanlab_studio.studio.studio.md: Expected corresponding JSX closing tag for . (9:160)
   7 |
   8 | {/* markdownlint-disable */}
>  9 | <a href="../../../cleanlab_studio/studio/studio#L0"></a>
     |                                                                                                                                                                 ^
  10 | <h1 {...{"id":"module-cleanlab_studiostudiostudio"}}><kbd>{`module`}</kbd>{` `}<inlineCode parentName="h1">{`cleanlab_studio.studio.studio`}</inlineCode></h1>
  11 | <p>{`Python API for Cleanlab Studio. `}</p>
  12 | <hr></hr>
SyntaxError: /Users/jay/workspaces/cleanlab-studio-docs/docs/autogenerated/reference/cleanlab_studio.studio.trustworthy_language_model.md: Expected corresponding JSX closing tag for . (9:180)
   7 |
   8 | {/* markdownlint-disable */}
>  9 | <a href="../../../cleanlab_studio/studio/trustworthy_language_model#L0"></a>
     |

**Comment by huiwengoh** [comment]
Ah, it's bc you need to run the docs built with the updated docs config changes too (https://github.com/cleanlab/cleanlab-studio-docs/pull/536).

It worked locally for me:
image

**Comment by jas2600** [comment]
> Ah, it's bc you need to run the docs built with the updated docs config https://github.com/cleanlab/cleanlab-studio-docs/pull/536 too.

I believe I used the `tlm-lite-rename` branch of the docs repo to generate and got that error. But right now it works. Is that related to [this change?](https://github.com/cleanlab/cleanlab-studio-docs/pull/536/commits/4ba3b21b5643e8c4fe86332e21a2c62ca844961c)

**Review by jas2600 — APPROVED** [review]

**Pull request merged**
